name: rpg_character_sheet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get:
  flutter_form_builder:
  hive_ce: 2.5.0+2
  hive_ce_flutter: 2.0.0
  form_builder_validators: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
